name: Link checker

on:
  schedule:
    - cron: '10 12 * * *'
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check hyperlinks
        run: go run .
