name: Go

# Reference: https://github.com/itchyny/gojq/blob/v0.12.17/.github/workflows/ci.yaml
on:
  push:
    branches: ["main"]
    tags: ["v*"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.18"

      - name: Formatted?
        run: |
          gofmt -l .
          test -z "`gofmt -l .`"

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...

      - name: Lint (staticcheck)
        uses: dominikh/staticcheck-action@v1.3.0
        with:
          install-go: true
          version: "2023.1.6"

  build-release:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # fetch all history for git describe
      - name: version
        run: make version
      - name: Cross build
        run: make cross
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: goxz
          path: goxz
      - name: Clean
        run: make clean

  release:
    needs: [test, build-release]
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          name: goxz
          path: goxz
      - name: Setup release body
        run: echo ${{ github.ref_name }} >release-body.txt
      - name: Create release
        uses: ncipollo/release-action@440c8c1cb0ed28b9f43e4d1d670870f059653174 # v1.16.0
        with:
          name: Release ${{ github.ref_name }}
          bodyFile: release-body.txt
          artifacts: goxz/*
