name: Go

'on':
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.18'

    - name: Formatted?
      run: |
        gofmt -l .
        test -z `gofmt -l .`

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...

    - name: Lint (staticcheck)
      uses: dominikh/staticcheck-action@v1.3.0
      with:
        install-go: true
        version: "2023.1.6"
